<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Dixels.Portal</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dixels.Portal.Domain\Dixels.Portal.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.MailKit" Version="10.6.1" />
    <PackageReference Include="Microsoft.Identity.Client" Version="4.90.1" />
    <PackageReference Include="System.Threading.RateLimiting" Version="10.0.9" />
  </ItemGroup>

</Project>
