<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Dixels.Portal</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Dixels.Portal.Domain\Dixels.Portal.Domain.csproj" />
    <ProjectReference Include="..\Dixels.Portal.TestBase\Dixels.Portal.TestBase.csproj" />
  </ItemGroup>

</Project>
